name: simple-todo-fastapi
channels:
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - sqlalchemy
  - pydantic
  - pandas
  - numpy
  - pip
  - pip:
      - aiofiles
      - python-dotenv
      - flake8
      - pytest
