name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: base

      - name: Install dependencies
        run: conda env update --file environment.yml --name base

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
